### ISSUE TITLE
Could you share your hardware connection?

### ISSUE THREAD

**Issue by chaos-adept** [kev-m/sharp-gp2y1010-esp8266#1]
first of all, thank you for sharing this code base, it is really useful!
it would be great to know how did you connect the board to the sensor. 
actually, the question mostly about using resistors, could you share this as a scheme like [fritzing](https://fritzing.org/projects/) does (or similar)

**Comment by kev-m** [comment]
Thank you for your interest.
Basically, I used the resistor and capacitor provided by the Alibaba supplier, wired according to figure 1 in the [reference PDF](https://global.sharp/products/device/lineup/data/pdf/datasheet/gp2y1010au_e.pdf).
I'll make this clearer in the README.

**Comment by kev-m** [comment]
Please see the updated README on [GitLab](https://gitlab.com/kev-m/sharp-gp2y1010-esp8266).
Does this answer your question?

**Comment by chaos-adept** [comment]
yes, it answers my question, mostly I looked for the connection from led turning on esp board to the sensor, I have found it.

Many thanks!
